[package]
name = "djed_enum_str_derive"
version = "0.1.0"
authors = ["Djedou <djedouarnaud.aman@gmail.com>"]

[lib]
name = "djed_enum_str_derive"
proc-macro = true

[dependencies]
heck = "0.3.0"
quote = "0.3.15"
syn = "0.11.11"
